name: front_end
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1

  # Firebase Services
  firebase_core: ^2.24.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.15.1
  firebase_storage: ^11.5.0
  
  #firebase_storage: ^11.5.0
  firebase_storage_web: ^3.6.23


  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.1.0

  # HTTP & Networking
  http: ^1.2.1

  # UI Components
  fl_chart: ^0.70.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # Location & Maps
  geolocator: ^11.1.0  # Use this stable version
  google_maps_flutter: ^2.5.0  # Compatible version
  geocoding: ^2.1.0

  # Media & Files
  image_picker: ^1.0.7
  file_picker: ^6.1.2
  path_provider: ^2.1.1

  # Permissions
  permission_handler: ^11.0.1

  # Web Support
  image_picker_web: ^3.0.6
  universal_html: ^2.2.1

  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic