name: front_end
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^5.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  fl_chart: ^0.70.2
  shared_preferences: ^2.0.0
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.1.1
  geolocator: ^8.2.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^10.4.0
  image_picker_web: ^3.0.1  # For web
  universal_html: ^2.2.1  #
  intl: ^0.18.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/burgger.jpg
    - assets/images/frys.jpg
    - assets/images/grill.jpg
    - assets/images/Juice.jpg
    - assets/images/juicy.jpg
    - assets/images/lit1.jpg
    - assets/images/meat.jpg
    - assets/images/PIZZA.jpg
    - assets/images/sungura.png
    - assets/images/table.jpg
    - assets/images/Airtelmoney.jpg
    - assets/images/MTN.jpg
    - assets/images/default.jpg
    - assets/images/Takeaway.jpg
    - assets/images/Delivery.jpg
    - assets/images/payment.png
    - assets/images/Chicken lollipops.jpg
    - assets/images/African Boiled chicken.jpg
    - assets/images/Chicken stewers.jpg
    - assets/images/Chickenwings.jpg
    - assets/images/drumsticks.jpg
    - assets/images/grilled chicken thigh.jpg
    - assets/images/panfried drumsticks.jpg
    - assets/images/Panfriedchicken.jpg
    - assets/images/Whole Grilled chicken.jpg
    - assets/images/deliver.png
    - assets/images/sungura1.png
    - assets/images/profile.png
    # - assets/images/placeholder.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic